In [1]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re

In [47]:
url = "https://www.timeanddate.com/holidays/jordan/2018"
headers = {'Accept-Language': 'en-US,en;q=0.5'}

In [48]:
html = requests.get(url, headers = headers)

In [49]:
soup = BeautifulSoup(html.text, 'lxml')

In [50]:
table = soup.find('table', id="holidays-table")

In [51]:
table_rows = table.find_all('tr', id = re.compile('^tr\d'))

In [41]:
table_rows[0]

In [53]:
date = []
weekday = []
holiday_name = []
holiday_type = []

for i in range(len(table_rows)):
    date.append(table_rows[i].find('th').text + ' ' + '2018')
    weekday.append(table_rows[i].find('td').text)
    holiday_name.append(table_rows[i].find('a').text)
    holiday_type.append(table_rows[i].find_all('td')[-1].text)

In [54]:
df = pd.DataFrame({'Date':date, 'Weekday':weekday, 'Holiday_name': holiday_name, 'Holiday_type':holiday_type})
df

           Date    Weekday            Holiday_name      Holiday_type
0    1 Jan 2018     Monday          New Year's Day  National holiday
1   20 Mar 2018    Tuesday           March Equinox            Season
2   25 Mar 2018     Sunday             Palm Sunday  Optional Holiday
3   30 Mar 2018     Friday             Good Friday        Observance
4    1 Apr 2018     Sunday           Easter Sunday        Observance
5    2 Apr 2018     Monday           Easter Monday        Observance
6    6 Apr 2018     Friday    Orthodox Good Friday        Observance
7    8 Apr 2018     Sunday     Orthodox Easter Day  Optional Holiday
8    9 Apr 2018     Monday  Orthodox Easter Monday  Optional Holiday
9   12 Apr 2018   Thursday      Al Isra' wal Miraj        Observance
10   1 May 2018    Tuesday              Labour Day  National holiday
11  16 May 2018  Wednesday          Ramadan begins        Observance
12  25 May 2018     Friday        Independence Day  National holiday
13  15 Jun 2018     Friday             Eid al-Fitr  National holiday
14  16 Jun 2018   Saturday     Eid al-Fitr holiday  National holiday
15  17 Jun 2018     Sunday     Eid al-Fitr holiday  National holiday
16  18 Jun 2018     Monday     Eid al-Fitr holiday  National holiday
17  21 Jun 2018   Thursday           June Solstice            Season
18  20 Aug 2018     Monday             Eid al-Adha  National holiday
19  21 Aug 2018    Tuesday     Eid al-Adha holiday  National holiday
20  22 Aug 2018  Wednesday     Eid al-Adha holiday  National holiday
21  23 Aug 2018   Thursday     Eid al-Adha holiday  National holiday
22  24 Aug 2018     Friday     Eid al-Adha holiday  National holiday
23  12 Sep 2018  Wednesday       Muharram/New Year  National holiday
24  23 Sep 2018     Sunday       September Equinox            Season
25  21 Nov 2018  Wednesday      Prophet's Birthday  National holiday
26  22 Dec 2018   Saturday       December Solstice            Season
27  25 Dec 2018    Tuesday           Christmas Day  National holiday
28  26 Dec 2018  Wednesday              Boxing Day  Optional Holiday

In [55]:
df['Date'] = pd.to_datetime(df['Date'])

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          29 non-null     datetime64[ns]
 1   Weekday       29 non-null     object
 2   Holiday_name  29 non-null     object
 3   Holiday_type  29 non-null     object
dtypes: datetime64[ns](1), object(3)
memory usage: 1.0+ KB

In [57]:
df.to_csv('Jordan_Holidays_2018.csv', index = False)

In [2]:
import pandas as pd
df1 = pd.read_csv(r'C:\Users\Sahil\Omdena\Detecting and Mitigating Traffic Accidents\datasets\Jordan_Holidays_2014.csv')
df2 = pd.read_csv(r'C:\Users\Sahil\Omdena\Detecting and Mitigating Traffic Accidents\datasets\Jordan_Holidays_2015.csv')
df3 = pd.read_csv(r'C:\Users\Sahil\Omdena\Detecting and Mitigating Traffic Accidents\datasets\Jordan_Holidays_2016.csv')
df4 = pd.read_csv(r'C:\Users\Sahil\Omdena\Detecting and Mitigating Traffic Accidents\datasets\Jordan_Holidays_2017.csv')
df5 = pd.read_csv(r'C:\Users\Sahil\Omdena\Detecting and Mitigating Traffic Accidents\datasets\Jordan_Holidays_2018.csv')

In [3]:
df = pd.concat([df1, df2, df3, df4, df5], axis = 0)
df

          Date    Weekday          Holiday_name      Holiday_type
0   2014-01-01  Wednesday        New Year's Day  National holiday
1   2014-01-13     Monday    Prophet's Birthday  National holiday
2   2014-03-20   Thursday         March Equinox            Season
3   2014-04-13     Sunday           Palm Sunday  Optional Holiday
4   2014-04-18     Friday  Orthodox Good Friday        Observance
..         ...        ...                   ...               ...
24  2018-09-23     Sunday     September Equinox            Season
25  2018-11-21  Wednesday    Prophet's Birthday  National holiday
26  2018-12-22   Saturday     December Solstice            Season
27  2018-12-25    Tuesday         Christmas Day  National holiday
28  2018-12-26  Wednesday            Boxing Day  Optional Holiday

[149 rows x 4 columns]

In [4]:
df.to_csv('Jordan_Holidays_2014_2018.csv', index = False)